baseURL = "http://example.org/"
languageCode = "en-us"
title = "The Slate Tablets"
theme = "m10c"

[params]
	author = "Slate"
	avatar = "../imgs/smokingwojak.jpg"
	description = "My personal blog site."
	menu_item_seperator = " - "
	[[params.social]]
		icon = "github"
		name = "Github"
		url = "https://github.com/5late"
